"""fixed relationships

Revision ID: a252e31288a4
Revises: 8df67b75fdf7
Create Date: 2025-05-23 14:41:24.162046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a252e31288a4'
down_revision = '8df67b75fdf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dev_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_freebie_dev_id_devs'), 'devs', ['dev_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_freebie_company_id_companies'), 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebie', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_freebie_company_id_companies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_freebie_dev_id_devs'), type_='foreignkey')
        batch_op.drop_column('dev_id')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
